function ppprtktest1 = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  PPPRTKTEST1 = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  PPPRTKTEST1 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  ppprtktest1 = importfile("/home/autobuntu/Documents/08032023/ppp_rtk_test_1.txt", [4, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 04-Aug-2023 09:52:41

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [4, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 29);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = [" ", "<"];

% Specify column names and types
opts.VariableNames = ["ICOM3",  "Msg",          "PORT",         "VarName4", "VarName5", "FINESTEERING", "VarName7",     "VarName8", "VarName9", "eb",       "VarName11",    "VarName12",    "VarName13",    "VarName14",    "VarName15",    "VarName16",    "VarName17",    "VarName18",    "VarName19",    "VarName20",    "VarName21",    "VarName22",    "VarName23",    "VarName24",    "VarName25",    "VarName26",    "VarName27",    "VarName28",    "VarName29"];
opts.VariableTypes = ["double", "categorical",  "categorical",  "double",   "double",   "categorical",  "categorical",  "string",   "double",   "double",   "double",       "double",       "string",       "double",       "double",       "double",       "string",       "double",       "double",       "double",       "double",       "double",       "double",       "double",       "double",       "double",       "double",       "double",       "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
ppprtktest1 = readtable(filename, opts);

end